import { useEffect, useMemo, useState } from 'react'

const seedRows = {
  Orders: [['#BM-1048', 'Ayesha Khan', 'Riyadh', '3 items', '$189.00', 'Pending'], ['#BM-1047', 'Omar Ali', 'Jeddah', '1 item', '$72.00', 'Shipped'], ['#BM-1046', 'Sara Malik', 'Dubai', '2 items', '$126.00', 'Delivered']],
  Customers: [['Ayesha Khan', 'ayesha@example.com', 'Riyadh', '4 orders', '$410.00'], ['Omar Ali', 'omar@example.com', 'Jeddah', '2 orders', '$188.00'], ['Sara Malik', 'sara@example.com', 'Dubai', '6 orders', '$720.00']],
  Reviews: [['Arc Mechanical Keyboard', 'Mariam H.', 'Great build quality and fast delivery.', 'Published'], ['Field Notes Desk Lamp', 'Bilal R.', 'Looks beautiful on my desk.', 'Pending']],
}

const labels = { Dashboard: 'Store overview', 'Import / Export': 'Move catalog data', Categories: 'Organize your catalog', 'Size Charts': 'Product sizing', Reviews: 'Customer feedback', Orders: 'Manage customer orders', Customers: 'Customer directory', Banners: 'Storefront promotions', Navigation: 'Store menus', 'Shipping & Tax': 'Checkout settings', Plugins: 'Apps and integrations' }

export default function AdminModules({ section, products, setNotice, api }) {
  const [categories, setCategories] = useState(['Computer Accessories', 'Home Decor', 'Bags & Travel', 'Everyday Carry', 'Textiles'])
  const [newCategory, setNewCategory] = useState('')
  const [menu, setMenu] = useState([])
  const [banner, setBanner] = useState({ title: 'New arrivals, thoughtfully chosen.', active: true })
  const [shipping, setShipping] = useState({ freeOver: 150, standard: 12, tax: 0 })
  const stats = useMemo(() => ({ products: products.length, published: products.filter((product) => product.is_active).length, stock: products.reduce((total, product) => total + Number(product.stock || 0), 0), featured: products.filter((product) => product.is_featured).length }), [products])
  useEffect(() => { api('/admin/categories').then(setCategories).catch(() => {}) }, [api])
  useEffect(() => { api('/admin/menu').then(setMenu).catch(() => {}) }, [api])

  if (section === 'Dashboard') return <div className="module-view"><div className="metric-grid"><Metric label="Total products" value={stats.products} detail="Catalog items" /><Metric label="Published" value={stats.published} detail="Visible online" /><Metric label="Inventory units" value={stats.stock} detail="Across all products" /><Metric label="Featured" value={stats.featured} detail="Homepage highlights" /></div><div className="module-card dashboard-card"><div className="module-card-heading"><div><p className="eyebrow">Recent activity</p><h3>Store at a glance</h3></div><span className="live-dot">Live catalog</span></div><div className="activity-list"><span>Catalog is connected to Laravel</span><strong>{stats.products} products loaded</strong><span>Publishing status</span><strong>{stats.published} products live</strong><span>Inventory health</span><strong>{stats.stock > 0 ? 'Healthy stock levels' : 'Needs attention'}</strong></div></div></div>

  if (section === 'Import / Export') return <div className="module-view"><div className="module-card"><div className="module-card-heading"><div><p className="eyebrow">Catalog tools</p><h3>Import and export</h3><p>Download a backup of your current catalog or prepare a spreadsheet for bulk editing.</p></div></div><div className="module-actions"><button className="button" onClick={() => { const blob = new Blob([JSON.stringify(products, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'baytmart-products.json'; link.click(); URL.revokeObjectURL(url); setNotice('Catalog export downloaded.') }}>Export JSON</button><button className="button secondary" onClick={() => setNotice('Bulk CSV import is ready for connection to your catalog API.')}>Import CSV</button></div></div></div>

  if (section === 'Categories') return <div className="module-view"><div className="module-card"><div className="module-card-heading"><div><p className="eyebrow">Catalog structure</p><h3>Categories</h3><p>Create collections that make products easy to discover.</p></div></div><div className="category-manager">{categories.map((category) => <div className="category-item" key={category.id || category.name}><span>{category.icon || '◇'}</span>{category.name || category}<button onClick={() => api(`/admin/categories/${category.id}`).then(() => setCategories(categories.filter((item) => item.id !== category.id)))}>Remove</button></div>)}</div><form className="add-row" onSubmit={(event) => { event.preventDefault(); if (newCategory.trim()) { api('/admin/categories', { method: 'POST', body: JSON.stringify({ name: newCategory, sort_order: categories.length, is_active: true }) }).then((saved) => { setCategories([...categories, saved]); setNewCategory('') }) } }}><input value={newCategory} onChange={(event) => setNewCategory(event.target.value)} placeholder="New category name" /><button className="button">Add category</button></form></div></div>

  if (section === 'Banners') return <div className="module-view"><div className="module-card banner-settings"><div className="module-card-heading"><div><p className="eyebrow">Storefront content</p><h3>Homepage banner</h3><p>Control the message displayed above your collection.</p></div><label className="switch"><input type="checkbox" checked={banner.active} onChange={(event) => setBanner({ ...banner, active: event.target.checked })} /><span /></label></div><label>Banner message<input value={banner.title} onChange={(event) => setBanner({ ...banner, title: event.target.value })} /></label><button className="button" onClick={() => setNotice('Banner settings saved.')}>Save banner</button></div></div>

  if (section === 'Navigation') return <div className="module-view"><div className="module-card"><div className="module-card-heading"><div><p className="eyebrow">Storefront content</p><h3>Navigation menus</h3><p>Toggle and rename the links shown in the customer header.</p></div></div><div className="category-manager">{menu.map((item) => <div className="category-item" key={item.id}><input value={item.label} onChange={(event) => setMenu(menu.map((entry) => entry.id === item.id ? { ...entry, label: event.target.value } : entry))} /><button onClick={() => api(`/admin/menu/${item.id}`, { method: 'DELETE' }).then(() => setMenu(menu.filter((entry) => entry.id !== item.id)))}>Remove</button></div>)}</div><button className="button" onClick={() => Promise.all(menu.map((item, index) => api('/admin/menu', { method: 'POST', body: JSON.stringify({ ...item, sort_order: index }) }))).then(() => setNotice('Navigation saved.'))}>Save navigation</button></div></div>

  if (section === 'Shipping & Tax') return <div className="module-view"><div className="module-card settings-card"><div className="module-card-heading"><div><p className="eyebrow">Checkout rules</p><h3>Shipping and tax</h3><p>These settings control the totals shown at checkout.</p></div></div><div className="settings-grid"><label>Free shipping over<input type="number" value={shipping.freeOver} onChange={(event) => setShipping({ ...shipping, freeOver: event.target.value })} /></label><label>Standard delivery<input type="number" value={shipping.standard} onChange={(event) => setShipping({ ...shipping, standard: event.target.value })} /></label><label>Tax rate %<input type="number" value={shipping.tax} onChange={(event) => setShipping({ ...shipping, tax: event.target.value })} /></label></div><button className="button" onClick={() => setNotice('Shipping and tax settings saved.')}>Save settings</button></div></div>

  if (section === 'Size Charts') return <TableModule section={section} columns={['Chart name', 'Products', 'Updated', 'Status']} rows={[['Standard fit', '12 products', 'Today', 'Active'], ['Accessories', '8 products', 'Yesterday', 'Active']]} />
  if (section === 'Reviews') return <TableModule section={section} columns={['Product', 'Customer', 'Review', 'Status']} rows={seedRows.Reviews} actions />
  if (section === 'Orders') return <TableModule section={section} columns={['Order #', 'Customer', 'City', 'Items', 'Total', 'Status']} rows={seedRows.Orders} actions />
  if (section === 'Customers') return <TableModule section={section} columns={['Customer', 'Email', 'City', 'Orders', 'Spent']} rows={seedRows.Customers} />
  if (section === 'Plugins') return <div className="module-view"><div className="module-card"><div className="module-card-heading"><div><p className="eyebrow">Extend your store</p><h3>Plugins and integrations</h3><p>Connect services for payments, analytics, email, and fulfillment.</p></div></div>{['Payments', 'Analytics', 'Email notifications', 'Shipping provider'].map((plugin) => <div className="plugin-row" key={plugin}><span><b>{plugin}</b><small>Not connected</small></span><button className="button secondary" onClick={() => setNotice(`${plugin} connection opened.`)}>Connect</button></div>)}</div></div>

  return <TableModule section={section} columns={['Name', 'Description', 'Status']} rows={[[section, labels[section], 'Ready']]} />
}

function Metric({ label, value, detail }) { return <div className="metric-card"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div> }
function TableModule({ section, columns, rows, actions = false }) { return <div className="module-view"><div className="module-card table-module"><div className="module-card-heading"><div><p className="eyebrow">Store operations</p><h3>{section}</h3><p>Manage this area of your BaytMart store.</p></div><button className="button secondary">Export</button></div><div className="module-data-table"><div className="module-table-row module-table-head">{columns.map((column) => <span key={column}>{column}</span>)}{actions && <span>Actions</span>}</div>{rows.map((row, index) => <div className="module-table-row" key={index}>{row.map((cell, cellIndex) => <span key={cellIndex}>{cell}</span>)}{actions && <span><button className="table-action">Review</button></span>}</div>)}</div></div></div> }
